services:
  kafka-1:
    image: kafka:latest
    container_name: kafka-1
    hostname: kafka-1
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_PROCESS_ROLES: "broker,controller"
      KAFKA_CONTROLLER_LISTENER_NAMES: CONTROLLER
      KAFKA_LISTENERS_SECURITY_PROTOCOL_MAP: "CONTROLLER:PLAINTEXT"
      KAFKA_LISTENERS: "PLAINTEXT://kafka-1:9092,CONTROLLER://kafka-1:9093"
      KAFKA_CONTROLLER_QUORUM_VOTERS: 1@kafka-1:9093
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
    networks:
      kafka-net:
        ipv4_address: 11.0.0.11
    healthcheck:
      test: /opt/kafka/bin/kafka-cluster.sh cluster-id --bootstrap-server kafka-1:9092 || exit 1
      interval: 5s
      retries: 60
  kafka-2:
    image: kafka:latest
    container_name: kafka-2
    hostname: kafka-2
    environment:
      KAFKA_BROKER_ID: 2
      KAFKA_PROCESS_ROLES: "broker"
      KAFKA_LISTENERS: "PLAINTEXT://kafka-2:9092"
      KAFKA_CONTROLLER_QUORUM_VOTERS: 1@kafka-1:9093
      KAFKA_CONTROLLER_LISTENER_NAMES: BROKER
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 3
    networks:
      kafka-net:
        ipv4_address: 11.0.0.12
    healthcheck:
      test: /opt/kafka/bin/kafka-cluster.sh cluster-id --bootstrap-server kafka-1:9092 || exit 1
      interval: 5s
      retries: 60
  kafka-3:
    image: kafka:latest
    container_name: kafka-3
    hostname: kafka-3
    environment:
      KAFKA_BROKER_ID: 3
      KAFKA_PROCESS_ROLES: "broker"
      KAFKA_LISTENERS: "PLAINTEXT://kafka-3:9092"
      KAFKA_CONTROLLER_QUORUM_VOTERS: 1@kafka-1:9093
      KAFKA_CONTROLLER_LISTENER_NAMES: BROKER
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 3
    networks:
      kafka-net:
        ipv4_address: 11.0.0.13
    healthcheck:
      test: /opt/kafka/bin/kafka-cluster.sh cluster-id --bootstrap-server kafka-1:9092 || exit 1
      interval: 5s
      retries: 60
  data_generator:
    container_name: data_generator
    hostname: data-generator
    image: data_generator:latest
    networks:
      kafka-net:
        ipv4_address: 11.0.0.14
    healthcheck:
      test: ["CMD", "curl", "-X", "POST", "-f", "http://localhost:5000/single"]
      interval: 2s
      retries: 60
  data_generator_client:
    container_name: data_generator_client
    hostname: data_generator_client
    image: pgsql_client:latest
    environment:
      DATA_TYPE: _banktest_transaction
      BATCH_SAVE_SIZE: 100 # saving # of records per batch
      BANK_TEST_NO_ACCOUNTS: 100
      DATA_GENERATOR_ENDPOINT: http://data-generator:5000 # !No trailing slash
      POSTGRES_HOST: state-tracker
      POSTGRES_PASSWORD: p
      POSTGRES_USER: u
      POSTGRES_DB: d
    networks:
      kafka-net:
        ipv4_address: 11.0.0.15
    depends_on:
      state-tracker:
        condition: service_healthy
      data_generator:
        condition: service_healthy
  state-tracker:
    container_name: state-tracker
    hostname: state-tracker
    image: docker.io/library/postgres:12.22
    environment:
      POSTGRES_PASSWORD: p
      POSTGRES_USER: u
      POSTGRES_DB: d
    networks:
      kafka-net:
        ipv4_address: 11.0.0.16
    healthcheck:
      test: ["CMD-SHELL", "pg_isready", "-d", "d", "-U", "u"]
      interval: 5s
      retries: 60
  producer:
    image: producer:latest
    hostname: producer
    container_name: producer
    environment:
      RUST_LOG: info
    entrypoint: /producer/target/debug/producer
    cap_add:
      - SYS_PTRACE
    networks:
      kafka-net:
        ipv4_address: 11.0.0.17
    depends_on:
      kafka-1:
        condition: service_healthy
      kafka-2:
        condition: service_healthy
      kafka-3:
        condition: service_healthy
  consumer:
    image: consumer:latest
    hostname: consumer
    container_name: consumer
    environment:
      RUST_LOG: info
    entrypoint: /consumer/target/debug/consumer
    networks:
      kafka-net:
        ipv4_address: 11.0.0.18
    depends_on:
      kafka-1:
        condition: service_healthy
      kafka-2:
        condition: service_healthy
      kafka-3:
        condition: service_healthy
      ddb:
        condition: service_healthy
  validator:
    image: validator:latest
    hostname: validator
    container_name: validator
    environment:
      - AWS_ACCESS_KEY_ID=dummy
      - AWS_SECRET_ACCESS_KEY=dummy
    networks:
      kafka-net:
        ipv4_address: 11.0.0.19
    depends_on:
      consumer:
        condition: service_started
        required: true
  ddb:
    container_name: ddb
    hostname: ddb
    image: docker.io/amazon/dynamodb-local:2.6.1
    ports:
      - "8000:8000"
    networks:
      kafka-net:
        ipv4_address: 11.0.0.20
    healthcheck:
      test:
        [
          "CMD-SHELL",
          'if [ "$(curl -s -o /dev/null -I -w ''%{http_code}'' http://localhost:8000)" == "400" ]; then exit 0; else exit 1; fi',
        ]
      interval: 5s
      retries: 20
  processor:
    image: processor:latest
    hostname: processor
    container_name: processor
    environment:
      RUST_LOG: info
    entrypoint: /processor/target/debug/processor
    cap_add:
      - SYS_PTRACE
    networks:
      kafka-net:
        ipv4_address: 11.0.0.22
    depends_on:
      kafka-1:
        condition: service_healthy
      kafka-2:
        condition: service_healthy
      kafka-3:
        condition: service_healthy
  ddd:
    container_name: ddd
    hostname: ddd
    image: ddd:latest
    entrypoint: sleep infinity
    networks:
      kafka-net:
        ipv4_address: 11.0.0.21
networks:
  kafka-net:
    driver: bridge
    ipam:
      config:
        - subnet: 11.0.0.0/24
