services:
  kafka-1:
    image: 'docker.io/apache/kafka:latest'
    container_name: kafka-1
    hostname: kafka-1
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_PROCESS_ROLES: "broker,controller"
      KAFKA_CONTROLLER_LISTENER_NAMES: CONTROLLER
      KAFKA_LISTENERS_SECURITY_PROTOCOL_MAP: "CONTROLLER:PLAINTEXT"
      KAFKA_LISTENERS: "PLAINTEXT://kafka-1:9092,CONTROLLER://kafka-1:9093"
      KAFKA_CONTROLLER_QUORUM_VOTERS: 1@kafka-1:9093
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
  kafka-2:
    image: 'docker.io/apache/kafka:latest'
    container_name: kafka-2
    hostname: kafka-2
    environment:
      KAFKA_BROKER_ID: 2
      KAFKA_PROCESS_ROLES: "broker"
      KAFKA_LISTENERS: "PLAINTEXT://kafka-2:9092"
      KAFKA_CONTROLLER_QUORUM_VOTERS: 1@kafka-1:9093
      KAFKA_CONTROLLER_LISTENER_NAMES: BROKER
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 3
  kafka-3:
    image: 'docker.io/apache/kafka:latest'
    container_name: kafka-3
    hostname: kafka-3
    environment:
      KAFKA_BROKER_ID: 3
      KAFKA_PROCESS_ROLES: "broker"
      KAFKA_LISTENERS: "PLAINTEXT://kafka-3:9092"
      KAFKA_CONTROLLER_QUORUM_VOTERS: 1@kafka-1:9093
      KAFKA_CONTROLLER_LISTENER_NAMES: BROKER
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 3
  state_tracker:
    container_name: state_tracker
    hostname: state_tracker
    image: docker.io/postgres:12.22
    environment:
      POSTGRES_PASSWORD: p
      POSTGRES_USER: u
      POSTGRES_DB: d
  data_generator:
    container_name: data_generator
    hostname: data_generator
    image: data_generator:latest
  data_generator_client:
    container_name: data_generator_client
    hostname: data_generator_client
    image: pgsql_client:latest
    environment:
      BATCH_SAVE_SIZE: 100 # saving # of records per batch
      DATA_GENERATOR_ENDPOINT: http://data_generator:5000 # !No trailing slash
      POSTGRES_HOST: state_tracker
      POSTGRES_PASSWORD: p
      POSTGRES_USER: u
      POSTGRES_DB: d
  producer:
    image: producer:latest
    hostname: producer
    container_name: producer
    environment:
      RUST_LOG: debug 
    # entrypoint: sleep infinity
    entrypoint: /producer/target/debug/producer
    cap_add:
      - SYS_PTRACE
  consumer:
    image: consumer:latest
    hostname: consumer
    container_name: consumer
    environment:
      RUST_LOG: debug 
    entrypoint: /consumer/target/debug/consumer
  validator:
    image: validator:latest
    hostname: validator
    container_name: validator
    # volumes:
    #   ../../workload/validator:/validator
    entrypoint: sleep infinity