version: '2'
services:
  kafka-1:
    image: kafka:latest
    container_name: kafka-1
    hostname: kafka-1
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_PROCESS_ROLES: "broker,controller"
      KAFKA_CONTROLLER_LISTENER_NAMES: CONTROLLER
      KAFKA_LISTENERS_SECURITY_PROTOCOL_MAP: "CONTROLLER:PLAINTEXT"
      KAFKA_LISTENERS: "PLAINTEXT://kafka-1:9092,CONTROLLER://kafka-1:9093"
      KAFKA_CONTROLLER_QUORUM_VOTERS: 1@kafka-1:9093
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
    networks:
      kafka-net:
        ipv4_address: 11.0.0.11
  kafka-2:
    image: kafka:latest
    container_name: kafka-2
    hostname: kafka-2
    environment:
      KAFKA_BROKER_ID: 2
      KAFKA_PROCESS_ROLES: "broker"
      KAFKA_LISTENERS: "PLAINTEXT://kafka-2:9092"
      KAFKA_CONTROLLER_QUORUM_VOTERS: 1@kafka-1:9093
      KAFKA_CONTROLLER_LISTENER_NAMES: BROKER
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 3
    networks:
      kafka-net:
        ipv4_address: 11.0.0.12
  kafka-3:
    image: kafka:latest
    container_name: kafka-3
    hostname: kafka-3
    environment:
      KAFKA_BROKER_ID: 3
      KAFKA_PROCESS_ROLES: "broker"
      KAFKA_LISTENERS: "PLAINTEXT://kafka-3:9092"
      KAFKA_CONTROLLER_QUORUM_VOTERS: 1@kafka-1:9093
      KAFKA_CONTROLLER_LISTENER_NAMES: BROKER
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 3
    networks:
      kafka-net:
        ipv4_address: 11.0.0.13
  data_generator:
    container_name: data_generator
    hostname: data-generator
    image: data_generator:latest
    entrypoint: ["flask", "--app", "base", "run", "--debug", "--host=0.0.0.0"]
    networks:
      kafka-net:
        ipv4_address: 11.0.0.14
  data_generator_client:
    container_name: data_generator_client
    hostname: data_generator_client
    image: pgsql_client:latest
    environment:
      DATA_TYPE: _banktest_transaction
      BATCH_SAVE_SIZE: 20 # saving # of records per batch
      BANK_TEST_NO_ACCOUNTS: 20
      DATA_GENERATOR_ENDPOINT: http://data-generator:5000 # !No trailing slash
      POSTGRES_HOST: state-tracker
      POSTGRES_PASSWORD: p
      POSTGRES_USER: u
      POSTGRES_DB: d
    networks:
      kafka-net:
        ipv4_address: 11.0.0.15
  state-tracker:
    container_name: state-tracker
    hostname: state-tracker
    image: docker.io/library/postgres:12.22
    environment:
      POSTGRES_PASSWORD: p
      POSTGRES_USER: u
      POSTGRES_DB: d
    networks:
      kafka-net:
        ipv4_address: 11.0.0.16
  producer:
    image: producer:latest
    hostname: producer
    container_name: producer
    environment:
      RUST_LOG: debug 
    entrypoint: /producer/target/debug/producer
    cap_add:
      - SYS_PTRACE
    networks:
      kafka-net:
        ipv4_address: 11.0.0.17
  consumer:
    image: consumer:latest
    hostname: consumer
    container_name: consumer
    environment:
      RUST_LOG: debug 
    entrypoint: /consumer/target/debug/consumer
    networks:
      kafka-net:
        ipv4_address: 11.0.0.18
  validator:
    image: validator:latest
    hostname: validator
    container_name: validator
    entrypoint: sleep infinity
    networks:
      kafka-net:
        ipv4_address: 11.0.0.19
networks:
  kafka-net:
    driver: bridge
    ipam:
      config:
        - subnet: 11.0.0.0/24
