name: Launch multiverse debugger (parsed)

on: 
  #manual run
  workflow_dispatch:
    inputs:
      input_string:
        description: 'Full moment'
        required: true
        type: string
      emails:
        type: string
        required: true
        description: Email receipents

jobs:
  manual_run:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - name: Extract values from moment
        id: extract
        run: |
          input="${{ github.event.inputs.input_string }}"
          
          session_id_1=$(echo "$input" | sed -n 's/.*session_id: "\([^"]*\)".*/\1/p')
          input_hash_1=$(echo "$input" | sed -n 's/.*input_hash: "\([^"]*\)".*/\1/p')
          vtime_1=$(echo "$input" | sed -n 's/.*vtime: \([0-9.]*\).*/\1/p')
          
          session_id_2=$(echo $input | sed -n 's/.*id: "\([^"]*\)".*/\1/p')
          input_hash_2=$(echo $input | sed -n "s/.*), *'\([^']*\)'.*/\1/p")
          vtime_2=$(echo $input | sed -n 's/.*,\s*\([0-9]*\.[0-9]*\).*/\1/p')
          
          echo "session_id=${session_id_1:-$session_id_2}" >> "$GITHUB_OUTPUT"
          echo "input_hash=${input_hash_1:-$input_hash_2}" >> "$GITHUB_OUTPUT"
          echo "vtime=${vtime_1:-$vtime_2}" >> "$GITHUB_OUTPUT"
      - uses: antithesishq/antithesis-trigger-action@main 
        with:
          notebook_name: launch_debugging
          tenant: demo
          username: ${{ secrets.ANTITHESIS_USER_NAME }}
          password: ${{ secrets.ANTITHESIS_PASSWORD }}
          github_token: ${{ secrets.GH_PAT }}
          description: "Debugging session from Github actions"
          email_recipients: demo-notifications.231bba29dc150b687d3f3d9370e63ada.show-sender@streams.zulipchat.com;${{ github.event.inputs.emails }}
          additional_parameters: |-
            antithesis.debugging.session_id=${{ steps.extract.outputs.session_id }}
            antithesis.debugging.input_hash=${{ steps.extract.outputs.input_hash }}
            antithesis.debugging.vtime=${{ steps.extract.outputs.vtime }}
