name: Launch multiverse debugger (parsed)

on: 
  #manual run
  workflow_dispatch:
    inputs:
      input_string:
        description: 'Full moment string (e.g., replay_moment = Moment._exact(...))'
        required: true
        type: string

jobs:
  manual_run:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - name: Extract values from moment
        id: extract
        run: |
          input="${{ github.event.inputs.input_string }}"
          session_id=$(echo $input | sed -n 's/.*id: \([^,}]*\).*/\1/p')
          value1=$(echo $input | sed -n "s/.*), *'\([^']*\)'.*/\1/p")
          value2=$(echo $input | sed -n 's/.*,\s*\([0-9]*\.[0-9]*\).*/\1/p')
      - uses: antithesishq/antithesis-trigger-action@main
        with:
          notebook_name: launch_debugging
          tenant: demo
          username: ${{ secrets.ANTITHESIS_USER_NAME }}
          password: ${{ secrets.ANTITHESIS_PASSWORD }}
          github_token: ${{ secrets.GH_PAT }}
          description: "Debugging session from Github actions"
          email_recipients: demo-notifications.231bba29dc150b687d3f3d9370e63ada.show-sender@streams.zulipchat.com;${{ github.event.inputs.emails }}
          additional_parameters: |-
            antithesis.debugging.session_id=${{ steps.extract.outputs.session_id }}
            antithesis.debugging.input_hash=${{ steps.extract.outputs.input_hash }}
            antithesis.debugging.vtime=${{ steps.extract.outputs.vtime }}
